### PR TITLE
feat: add track analysis using gtp3

### PR DESCRIPTION
**Pull request by laurentlucian**
as each AI query is paid, there's an implementation of cache using the existing redis system (fly.io doesn't have CDNs)

### CODE REVIEW

**Comment by laurentlucian** [comment]
Current dependencies on/for this PR:
* main
  * **PR #11** <a href="https://app.graphite.dev/github/pr/laurentlucian/musy/11" target="_blank">Graphite</a> 
    * **PR #12** <a href="https://app.graphite.dev/github/pr/laurentlucian/musy/12" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/laurentlucian/musy/12?utm_source=stack-comment).

**Comment by laurentlucian** [comment]
**Graphite Merge Job**

Current status: ⚠️ Downstack blocker

A downstack pull request blocked this pull request from being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/laurentlucian/musy/12?utm_source=stack-comment).


Job Reference: 8W40LvMHSYLixviLIMap

**Comment by laurentlucian** [comment]
**Graphite Merge Job**

Current status: ✅ Merged

This pull request was successfully merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/laurentlucian/musy/12?utm_source=stack-comment).


Job Reference: uASo2UY6jtgowYMJhyPY

**Comment by danielbuva** [comment]
interesting

**Pull request merged**
